async function request(path,options={}){
  const r=await fetch(path,{headers:{'Content-Type':'application/json',...(options.headers||{})},...options});
  let data=null; try{data=await r.json()}catch{data={error:'Geçersiz sunucu yanıtı'}}
  if(!r.ok) throw new Error(data?.error||('HTTP '+r.status));
  return data;
}
export const api={
  summary:()=>request('/api/summary'),
  brief:()=>request('/api/brief'),
  search:q=>request('/api/search?q='+encodeURIComponent(q)),
  clients:()=>request('/api/clients'),
  client:id=>request('/api/clients/'+id),
  powers:()=>request('/api/powers'),
  power:id=>request('/api/powers/'+id),
  assets:()=>request('/api/assets'),
  asset:id=>request('/api/assets/'+id),
  officeFiles:()=>request('/api/office-files'),
  officeFile:id=>request('/api/office-files/'+id),
  createOfficeFile:body=>request('/api/office-files',{method:'POST',body:JSON.stringify(body)}),
  timeline:id=>request('/api/office-files/'+id+'/timeline'),
  archiveStandard:()=>request('/api/archive/standard'),
  scanArchive:()=>request('/api/archive/scan',{method:'POST',body:'{}'}),
  archiveSuggestions:id=>request('/api/archive/suggestions?officeFileId='+encodeURIComponent(id)),
  verifyArchiveLink:id=>request('/api/archive/links/'+id+'/verify',{method:'POST',body:'{}'}),
  syncProfile:caseId=>request('/api/cases/'+caseId+'/sync-profile'),
  baselineStatus:caseId=>request('/api/cases/'+caseId+'/sync-baseline-status'),
  remoteDocuments:(caseId,onlyNew=true)=>request('/api/cases/'+caseId+'/remote-documents?onlyNew='+(onlyNew?'1':'0')),
  correspondence:id=>request('/api/office-files/'+id+'/correspondence'),
  createCorrespondence:body=>request('/api/correspondence',{method:'POST',body:JSON.stringify(body)}),
  markCorrespondenceResponse:(id,body={})=>request('/api/correspondence/'+id+'/response',{method:'POST',body:JSON.stringify(body)}),
  evidenceMatrix:id=>request('/api/office-files/'+id+'/evidence-matrix'),
  createEvidenceIssue:body=>request('/api/evidence/issues',{method:'POST',body:JSON.stringify(body)}),
  addEvidenceLink:(id,body)=>request('/api/evidence/issues/'+id+'/links',{method:'POST',body:JSON.stringify(body)}),
  representationRadar:id=>request('/api/office-files/'+id+'/representation-radar'),
  linkPowerToCase:(caseId,powerId)=>request('/api/cases/'+caseId+'/link-power',{method:'POST',body:JSON.stringify({powerId})}),
  deadlines:()=>request('/api/deadlines'),
  calculateDeadline:body=>request('/api/deadlines/calculate',{method:'POST',body:JSON.stringify(body)}),
  saveCalculatedDeadline:body=>request('/api/deadlines/calculate-and-save',{method:'POST',body:JSON.stringify(body)}),
  legalCalendar:()=>request('/api/legal-calendar'),
  tasks:()=>request('/api/tasks'),
  jobs:()=>request('/api/jobs'),
  roots:()=>request('/api/scan-roots'),
  audit:()=>request('/api/audit'),
  intelligenceStatus:()=>request('/api/intelligence/status'),
  templates:()=>request('/api/intelligence/templates'),
  template:id=>request('/api/intelligence/templates/'+id),
  setTemplateOfficeStyle:(id,enabled)=>request('/api/intelligence/templates/'+id+'/office-style',{method:'POST',body:JSON.stringify({enabled})}),
  knowledgeSearch:(q,filters={})=>request('/api/knowledge/search?'+new URLSearchParams({q,...Object.fromEntries(Object.entries(filters).filter(([,v])=>v!=null&&v!==''))})),
  documentAnalysis:id=>request('/api/assets/'+id+'/analysis'),
  drafts:()=>request('/api/drafts'),
  draft:id=>request('/api/drafts/'+id),
  createDraft:body=>request('/api/drafts',{method:'POST',body:JSON.stringify(body)}),
  updateDraft:(id,body)=>request('/api/drafts/'+id,{method:'PUT',body:JSON.stringify(body)}),
  exportDraftUdf:id=>request('/api/drafts/'+id+'/export-udf',{method:'POST',body:'{}'}),
  notes:filters=>request('/api/notes?'+new URLSearchParams(Object.fromEntries(Object.entries(filters||{}).filter(([,v])=>v!=null&&v!=='')))),
  createNote:body=>request('/api/notes',{method:'POST',body:JSON.stringify(body)}),
  clientFinance:id=>request('/api/clients/'+id+'/finance'),
  financeOverview:()=>request('/api/finance/overview'),
  createFeeContract:body=>request('/api/fee-contracts',{method:'POST',body:JSON.stringify(body)}),
  createFinancialEntry:body=>request('/api/financial-entries',{method:'POST',body:JSON.stringify(body)}),
  communications:filters=>request('/api/communications?'+new URLSearchParams(Object.fromEntries(Object.entries(filters||{}).filter(([,v])=>v!=null&&v!=='')))),
  createCommunication:body=>request('/api/communications',{method:'POST',body:JSON.stringify(body)}),
  communicationStatus:()=>request('/api/communication-status'),
  relations:id=>request('/api/clients/'+id+'/relations'),
  createRelation:body=>request('/api/relations',{method:'POST',body:JSON.stringify(body)}),
  refreshMergeCandidates:()=>request('/api/merge-candidates/refresh',{method:'POST',body:'{}'}),
  mergeCandidates:()=>request('/api/merge-candidates'),
  aiPermissions:()=>request('/api/ai/permissions'),
  setAiPermission:(capability,body)=>request('/api/ai/permissions/'+encodeURIComponent(capability),{method:'POST',body:JSON.stringify(body)}),
  generateHearingPack:id=>request('/api/office-files/'+id+'/hearing-pack',{method:'POST',body:'{}'}),
  hearingPacks:id=>request('/api/office-files/'+id+'/hearing-packs'),
  hearingPack:id=>request('/api/hearing-packs/'+id),
  serviceHealth:()=>request('/api/service-health'),
  uyapStatus:()=>request('/api/uyap/status'),
  uyapObservations:()=>request('/api/uyap/observations?limit=40'),
  uyapCases:()=>request('/api/uyap/cases'),
  uyapRemoteDocuments:caseId=>request('/api/uyap/cases/'+encodeURIComponent(caseId)+'/remote-documents'),
  syncUyapDocuments:caseId=>request('/api/uyap/cases/'+encodeURIComponent(caseId)+'/sync-documents',{method:'POST',body:'{}'}),
  downloadUyapDocument:id=>request('/api/uyap/remote-documents/'+encodeURIComponent(id)+'/download',{method:'POST',body:'{}'}),
  eventBusStatus:()=>request('/api/event-bus/status'),
  shipments:(filters={})=>request('/api/tebligatlar?'+new URLSearchParams(Object.fromEntries(Object.entries(filters).filter(([,v])=>v!=null&&v!=='')))),
  providerStatus:()=>request('/api/v06/provider-status'),
  workRadar:(filters={})=>request('/api/work-radar?'+new URLSearchParams(Object.fromEntries(Object.entries(filters).filter(([,v])=>v!=null&&v!=='')))),
  resolveWorkRadar:id=>request('/api/work-radar/'+id+'/resolve',{method:'POST',body:'{}'}),
  workflows:()=>request('/api/workflows'),
  workflow:id=>request('/api/workflows/'+id),
  workflowRuns:(limit=100)=>request('/api/workflow-runs?limit='+encodeURIComponent(limit)),
  workflowApprovals:()=>request('/api/workflow-approvals'),
  triggerWorkflow:(key,input={})=>request('/api/workflows/'+encodeURIComponent(key)+'/trigger',{method:'POST',body:JSON.stringify({input})}),
  decideWorkflowApproval:(id,approved,note='')=>request('/api/workflow-approvals/'+id,{method:'POST',body:JSON.stringify({approved,note})}),
  morningBrief:()=>request('/api/morning-brief'),
  upcomingHearings:(limit=30)=>request('/api/hearings/upcoming?limit='+encodeURIComponent(limit)),
  hearingCockpit:id=>request('/api/hearings/'+id+'/cockpit'),
  scanInterimOrders:body=>request('/api/interim-orders/scan',{method:'POST',body:JSON.stringify(body||{})}),
  interimOrders:(officeFileId=null)=>request('/api/interim-orders?'+new URLSearchParams({status:'open',...(officeFileId?{officeFileId}: {})})),
  resolveInterimOrder:id=>request('/api/interim-orders/'+id+'/resolve',{method:'POST',body:'{}'}),
  scanCorrespondenceMatches:body=>request('/api/correspondence-matches/scan',{method:'POST',body:JSON.stringify(body||{})}),
  correspondenceMatches:(officeFileId=null)=>request('/api/correspondence-matches'+(officeFileId?'?officeFileId='+encodeURIComponent(officeFileId):'')),
  decideCorrespondenceMatch:(id,approved)=>request('/api/correspondence-matches/'+id,{method:'POST',body:JSON.stringify({approved})}),
  scanNotificationDocuments:body=>request('/api/notification-extraction/scan',{method:'POST',body:JSON.stringify(body||{})}),
  backupHealth:()=>request('/api/system/backup-health'),
  checkpoints:()=>request('/api/system/checkpoints'),
  createCheckpoint:(label='Manuel geri dönüş noktası')=>request('/api/system/checkpoints',{method:'POST',body:JSON.stringify({label})}),
  requestRestore:(id,confirmation)=>request('/api/system/checkpoints/'+id+'/restore-request',{method:'POST',body:JSON.stringify({confirmation})}),
  enqueue:(jobType,payload={},fingerprint=null,priority=100)=>request('/api/jobs',{method:'POST',body:JSON.stringify({jobType,payload,fingerprint,priority})}),
  createTask:body=>request('/api/tasks',{method:'POST',body:JSON.stringify(body)}),
  approveDeadline:id=>request('/api/deadlines/'+id+'/approve',{method:'POST',body:'{}'})
};