import {api} from '../api.js';
import {mount,pageHero,section,empty,esc,badge} from '../ui.js';

const money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',maximumFractionDigits:2}).format(Number(n||0));
export async function renderClients(id){
 if(id)return renderClient(id);
 const rows=await api.clients();
 const body=rows.length?`<div class="data-table"><div class="data-head"><span>Müvekkil</span><span>Vekâlet</span><span>Dosya</span><span></span></div>${rows.map(r=>`<a class="data-row" href="#clients/${r.id}"><span><strong>${esc(r.display_name)}</strong><small>${esc(r.client_type||'person')}</small></span><span>${r.power_count}</span><span>${r.case_count}</span><span>→</span></a>`).join('')}</div>`:empty('Müvekkil kaydı yok.');
 mount(pageHero('Müvekkiller','Vekâlet, dosya, sözleşme, tahsilat, iletişim ve notları tek müvekkil kimliğinde birleştir.')+section('Müvekkil Listesi','♙',body),'clients');
}
async function renderClient(id){
 const [c,fin,comms,rels,notes,commStatus]=await Promise.all([api.client(id),api.clientFinance(id),api.communications({clientId:id}),api.relations(id),api.notes({clientId:id}),api.communicationStatus()]);
 const powers=c.powers.length?c.powers.map(p=>`<a class="notice-row clickable" href="#powers/${p.id}"><div><div class="doc-title">${esc(p.notary||'Vekâlet')}</div><div class="doc-meta">Yevmiye ${esc(p.journal_no||'—')} · ${esc(p.issued_at||'—')} · ${p.source_count} kaynak</div></div>${badge(p.status||'active')}</a>`).join(''):empty('Bağlı vekâlet yok.');
 const cases=c.cases.length?c.cases.map(x=>`<div class="notice-row"><div><div class="doc-title">${esc(x.court||'UYAP Dosyası')}</div><div class="doc-meta">${esc(x.court_file_no||'')} · ${esc(x.case_type||'')}</div></div>${badge(x.status||'')}</div>`).join(''):empty('UYAP dosyası henüz bağlanmadı.');
 const contracts=fin.contracts.length?fin.contracts.map(x=>`<div class="notice-row"><div><div class="doc-title">${esc(x.title)}</div><div class="doc-meta">${esc(x.signed_at||'Tarih yok')} · ${x.file_count} föy</div></div><strong>${money(x.total_fee)}</strong></div>`).join(''):empty('Avukatlık ücret sözleşmesi yok.');
 const commBody=comms.length?comms.slice(0,10).map(x=>`<div class="notice-row"><div><div class="doc-title">${esc(x.channel)} · ${esc(x.subject||x.direction||'İletişim')}</div><div class="doc-meta">${esc(x.occurred_at)}${x.body?' · '+esc(x.body.slice(0,120)):''}</div></div></div>`).join(''):empty('İletişim kaydı yok.');
 const notesBody=notes.length?notes.slice(0,10).map(n=>`<div class="note-item"><div class="doc-title">${esc(n.title||'Not')}</div><div class="doc-meta">${esc(n.body)}</div></div>`).join(''):empty('Not yok.');
 const relBody=rels.length?rels.map(r=>`<div class="notice-row"><div><div class="doc-title">${esc(r.related_client_name||r.related_name||'İlişkili kişi')}</div><div class="doc-meta">${esc(r.relation_type)} · ${esc(r.office_file_no||'')}</div></div></div>`).join(''):empty('İlişkili kişi/kurum kaydı yok.');
 const wa=commStatus.whatsapp||{};
 mount(`<div class="case-header"><div class="crumb"><a href="#clients">Müvekkiller</a> / #${c.id}</div><h1>${esc(c.display_name)}</h1><div class="chips"><span class="chip">${c.powers.length} vekâlet</span><span class="chip">${c.cases.length} UYAP dosyası</span><span class="chip">${fin.contracts.length} sözleşme</span><span class="chip">Bakiye ${money(fin.totals.open)}</span></div></div>`+
 `<div class="client-dashboard"><div class="section-stack">${section('UYAP Dosyaları','□',cases)}${section('Vekâletler','♙',powers)}${section('Avukatlık Sözleşmeleri ve Hesap','₺',`<div class="finance-strip"><div><small>Kararlaştırılan</small><strong>${money(fin.totals.contracted)}</strong></div><div><small>Tahsil</small><strong>${money(fin.totals.paid)}</strong></div><div><small>Bakiye</small><strong>${money(fin.totals.open)}</strong></div></div>${contracts}`,'<div class="head-actions"><button id="clientContract" class="subtle-action">Sözleşme</button><button id="clientPayment" class="primary-action">Tahsilat</button></div>')}</div>`+
 `<div class="section-stack">${section('İletişim','✉',`<div class="connector-inline"><span>WhatsApp Business: ${esc(wa.status||'not_connected')}</span></div>${commBody}`,'<button id="clientComm" class="subtle-action">Kayıt Ekle</button>')}${section('Notlar','✎',notesBody,'<button id="clientNote" class="subtle-action">Not Ekle</button>')}${section('İlişkiler','◎',relBody,'<button id="clientRelation" class="subtle-action">İlişki Ekle</button>')}</div></div>`,'clients');
 document.querySelector('#clientNote').onclick=()=>noteModal(c.id);document.querySelector('#clientComm').onclick=()=>commModal(c.id);document.querySelector('#clientContract').onclick=()=>contractModal(c.id);document.querySelector('#clientPayment').onclick=()=>paymentModal(c.id);document.querySelector('#clientRelation').onclick=()=>relationModal(c.id);
}
function modalShell(title,body){const w=document.createElement('div');w.className='modal-backdrop';w.innerHTML=`<div class="modal"><h2>${title}</h2>${body}<div id="mErr" class="form-error"></div></div>`;document.body.appendChild(w);return w}
function noteModal(clientId){const w=modalShell('Müvekkil Notu',`<label>Başlık<input id="nTitle"></label><label>Not<textarea id="nBody" rows="5"></textarea></label><div class="modal-actions"><button id="mCancel">Vazgeç</button><button id="mSave" class="primary-action">Kaydet</button></div>`);w.querySelector('#mCancel').onclick=()=>w.remove();w.querySelector('#mSave').onclick=async()=>{try{await api.createNote({clientId,title:w.querySelector('#nTitle').value,body:w.querySelector('#nBody').value});w.remove();renderClient(clientId)}catch(e){w.querySelector('#mErr').textContent=e.message}}}
function commModal(clientId){const w=modalShell('İletişim Kaydı',`<label>Kanal<select id="cChannel"><option>WhatsApp</option><option>Telefon</option><option>E-posta</option><option>Toplantı</option></select></label><label>Konu<input id="cSubject"></label><label>Not<textarea id="cBody" rows="4"></textarea></label><div class="modal-actions"><button id="mCancel">Vazgeç</button><button id="mSave" class="primary-action">Kaydet</button></div>`);w.querySelector('#mCancel').onclick=()=>w.remove();w.querySelector('#mSave').onclick=async()=>{try{await api.createCommunication({clientId,channel:w.querySelector('#cChannel').value,direction:'manual',occurredAt:new Date().toISOString(),subject:w.querySelector('#cSubject').value,body:w.querySelector('#cBody').value});w.remove();renderClient(clientId)}catch(e){w.querySelector('#mErr').textContent=e.message}}}
async function contractModal(clientId){
 const files=await api.officeFiles();
 const opts=files.map(f=>`<option value="${f.id}">${esc((f.file_no||'—')+' · '+f.title)}</option>`).join('');
 const w=modalShell('Avukatlık Ücret Sözleşmesi',`<label>Başlık<input id="fTitle" value="Avukatlık Ücret Sözleşmesi"></label><label>Kapsadığı Föyler<select id="fFiles" multiple size="5">${opts}</select></label><div class="doc-meta">Bir sözleşme birden fazla föyü kapsayabilir.</div><label>Toplam ücret<input id="fTotal" type="number" step="0.01"></label><label>İmza tarihi<input id="fDate" type="date"></label><label>Ödeme planı<textarea id="fTerms" rows="3"></textarea></label><div class="modal-actions"><button id="mCancel">Vazgeç</button><button id="mSave" class="primary-action">Kaydet</button></div>`);
 w.querySelector('#mCancel').onclick=()=>w.remove();
 w.querySelector('#mSave').onclick=async()=>{try{
   const officeFileIds=[...w.querySelector('#fFiles').selectedOptions].map(o=>Number(o.value));
   await api.createFeeContract({clientId,title:w.querySelector('#fTitle').value,totalFee:Number(w.querySelector('#fTotal').value||0),signedAt:w.querySelector('#fDate').value||null,paymentTerms:w.querySelector('#fTerms').value||null,officeFileIds});
   w.remove();renderClient(clientId);
  }catch(e){w.querySelector('#mErr').textContent=e.message}};
}
function paymentModal(clientId){const w=modalShell('Tahsilat',`<label>Tutar<input id="pAmount" type="number" step="0.01"></label><label>Açıklama<input id="pDesc"></label><div class="modal-actions"><button id="mCancel">Vazgeç</button><button id="mSave" class="primary-action">Kaydet</button></div>`);w.querySelector('#mCancel').onclick=()=>w.remove();w.querySelector('#mSave').onclick=async()=>{try{await api.createFinancialEntry({clientId,entryType:'tahsilat',amount:Number(w.querySelector('#pAmount').value),paidAt:new Date().toISOString(),status:'paid',description:w.querySelector('#pDesc').value});w.remove();renderClient(clientId)}catch(e){w.querySelector('#mErr').textContent=e.message}}}
function relationModal(clientId){const w=modalShell('İlişki Ekle',`<label>İlişkili kişi/kurum<input id="rName"></label><label>İlişki türü<input id="rType" placeholder="karşı taraf / şirket / aile / bağlantılı dosya"></label><label>Not<textarea id="rNote" rows="3"></textarea></label><div class="modal-actions"><button id="mCancel">Vazgeç</button><button id="mSave" class="primary-action">Kaydet</button></div>`);w.querySelector('#mCancel').onclick=()=>w.remove();w.querySelector('#mSave').onclick=async()=>{try{await api.createRelation({clientId,relatedName:w.querySelector('#rName').value,relationType:w.querySelector('#rType').value,notes:w.querySelector('#rNote').value});w.remove();renderClient(clientId)}catch(e){w.querySelector('#mErr').textContent=e.message}}}