import {api} from '../api.js';
import {mount,pageHero,section,empty,esc,badge} from '../ui.js';

export async function renderDeadlines(){
 const [ds,ts,cal]=await Promise.all([api.deadlines(),api.tasks(),api.legalCalendar()]);
 const dbody=ds.length?ds.map(d=>`<div class="notice-row"><div><div class="doc-title">${esc(d.title)}</div><div class="doc-meta">${esc(d.due_at||'Tarih yok')} · ${esc(d.office_file_no||d.court_file_no||'Dosya yok')} ${d.legal_basis?'· '+esc(d.legal_basis):''}</div></div><div class="row-actions">${badge(d.lawyer_approved?'Avukat Onaylı':'Taslak',d.lawyer_approved?'green':'')} ${!d.lawyer_approved?`<button class="approve-deadline" data-id="${d.id}">Onayla</button>`:''}</div></div>`).join(''):empty('Hukuki süre kaydı yok.');
 const tbody=ts.length?ts.map(t=>`<div class="notice-row"><div><div class="doc-title">${esc(t.title)}</div><div class="doc-meta">${esc(t.due_at||'Tarih yok')} · ${esc(t.office_file_no||t.court_file_no||'Genel görev')} · ${esc(t.priority||'normal')}</div></div>${badge(t.status||'open')}</div>`).join(''):empty('Görev kaydı yok.');
 const da='<div class="head-actions"><button id="calcDeadline" class="subtle-action">Süre Hesapla</button></div>';
 const ta='<button id="newTaskBtn" class="primary-action">Yeni Görev</button>';
 const calInfo=`<div class="empty">Doğrulanmış özel/resmî takvim günü: <strong>${cal.filter(x=>x.verified_at).length}</strong><br><br>Takvim verisi yoksa motor hafta sonunu hesaplar ve ayrıca uyarı verir. Son tarih daima taslak kalır.</div>`;
 mount(pageHero('Süreler ve Görevler','Hukuki süre hesabı adım adım açıklanır; sistem onay yerine hesap taslağı üretir.')+`<div class="grid"><div class="section-stack">${section('Hukuki Süreler','◷',dbody,da)}${section('Hesap Güvenliği','⚖',calInfo)}</div><div>${section('Görevler','✓',tbody,ta)}</div></div>`,'deadlines');
 document.querySelectorAll('.approve-deadline').forEach(b=>b.onclick=async()=>{if(!confirm('Bu hukuki süreyi kontrol edip onayladığını teyit ediyor musun?'))return;b.disabled=true;try{await api.approveDeadline(b.dataset.id);renderDeadlines()}catch(e){alert(e.message);b.disabled=false}});
 document.querySelector('#newTaskBtn').onclick=taskModal;document.querySelector('#calcDeadline').onclick=deadlineModal;
}
function deadlineModal(){
 const w=document.createElement('div');w.className='modal-backdrop';w.innerHTML=`<div class="modal modal-wide"><h2>Şeffaf Süre Hesaplama</h2><div class="form-grid"><label>Başlık<input id="dlTitle" placeholder="İstinaf başvuru süresi"></label><label>Hukuki dayanak<input id="dlBasis" placeholder="Kontrol için madde/kanun notu"></label><label>Sistemde görülen / ulaştığı tarih<input id="dlTrigger" type="date"></label><label>Tebligat türü<select id="dlMode"><option value="manual">Manuel / normal başlangıç</option><option value="uets">UETS (+5 kanuni tebliğ)</option></select></label><label>Süre (gün)<input id="dlDays" type="number" min="0" max="3650" value="14"></label><label><input id="dlNext" type="checkbox" checked> Sayımı ertesi gün başlat</label><label><input id="dlAdjust" type="checkbox" checked> Son gün çalışma dışıysa ileri al</label></div><div id="dlPreview" class="deadline-preview"></div><div class="modal-actions"><button id="dlCancel">Vazgeç</button><button id="dlCalc" class="subtle-action">Hesapla</button><button id="dlSave" class="primary-action" disabled>Taslak Kaydet</button></div><div id="dlErr" class="form-error"></div></div>`;document.body.appendChild(w);
 const payload=()=>({title:w.querySelector('#dlTitle').value,legalBasis:w.querySelector('#dlBasis').value||null,triggerDate:w.querySelector('#dlTrigger').value,deliveryMode:w.querySelector('#dlMode').value,periodDays:Number(w.querySelector('#dlDays').value),countFromNextDay:w.querySelector('#dlNext').checked,adjustNonWorkingDay:w.querySelector('#dlAdjust').checked});
 w.querySelector('#dlCancel').onclick=()=>w.remove();
 w.querySelector('#dlCalc').onclick=async()=>{try{const r=await api.calculateDeadline(payload());w.dataset.ready='1';w.querySelector('#dlSave').disabled=false;w.querySelector('#dlPreview').innerHTML=`<div class="analysis-score"><strong>${esc(r.dueDate)}</strong><span>Taslak son gün</span></div>${r.trace.map(t=>`<div class="trace-row"><span>${esc(t.date||t.from||'')}</span><strong>${esc(t.label)}</strong></div>`).join('')}<div class="warning-box">${r.warnings.map(x=>`<p>⚠ ${esc(x)}</p>`).join('')}</div>`}catch(e){w.querySelector('#dlErr').textContent=e.message}};
 w.querySelector('#dlSave').onclick=async()=>{try{await api.saveCalculatedDeadline(payload());w.remove();renderDeadlines()}catch(e){w.querySelector('#dlErr').textContent=e.message}};
}
function taskModal(){const w=document.createElement('div');w.className='modal-backdrop';w.innerHTML=`<div class="modal"><h2>Yeni Görev</h2><label>Görev<input id="taskTitle" placeholder="Müvekkili ara"></label><label>Son tarih<input id="taskDue" type="datetime-local"></label><label>Öncelik<select id="taskPriority"><option>normal</option><option>high</option><option>low</option></select></label><div class="modal-actions"><button id="cancelTask">Vazgeç</button><button id="saveTask" class="primary-action">Oluştur</button></div><div id="taskError" class="form-error"></div></div>`;document.body.appendChild(w);document.querySelector('#cancelTask').onclick=()=>w.remove();document.querySelector('#saveTask').onclick=async()=>{const b=document.querySelector('#saveTask');b.disabled=true;try{await api.createTask({title:document.querySelector('#taskTitle').value,dueAt:document.querySelector('#taskDue').value||null,priority:document.querySelector('#taskPriority').value});w.remove();renderDeadlines()}catch(e){document.querySelector('#taskError').textContent=e.message;b.disabled=false}}}