const db=require("./db");const jobs=require("./jobs");
function all(s,...a){return db.prepare(s).all(...a)} function one(s,...a){return db.prepare(s).get(...a)}
function parse(s,d={}){try{return JSON.parse(s||"")}catch{return d}}
function audit(action,type,id,detail){db.prepare("INSERT INTO audit_log(occurred_at,actor,action,entity_type,entity_id,detail_json) VALUES(datetime('now'),'system',?,?,?,?)").run(action,type,id==null?null:String(id),JSON.stringify(detail||{}))}
function init(){db.exec(`
CREATE TABLE IF NOT EXISTS workflow_definitions(id INTEGER PRIMARY KEY,key TEXT UNIQUE NOT NULL,name TEXT NOT NULL,description TEXT,trigger_type TEXT NOT NULL,trigger_config_json TEXT,enabled INTEGER NOT NULL DEFAULT 1,version INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT(datetime('now')),updated_at TEXT NOT NULL DEFAULT(datetime('now')));
CREATE TABLE IF NOT EXISTS workflow_steps(id INTEGER PRIMARY KEY,workflow_id INTEGER NOT NULL,step_order INTEGER NOT NULL,step_key TEXT NOT NULL,step_type TEXT NOT NULL,config_json TEXT,requires_approval INTEGER NOT NULL DEFAULT 0,on_error TEXT NOT NULL DEFAULT 'stop',UNIQUE(workflow_id,step_order),FOREIGN KEY(workflow_id) REFERENCES workflow_definitions(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS workflow_runs(id INTEGER PRIMARY KEY,workflow_id INTEGER NOT NULL,trigger_type TEXT,trigger_ref TEXT,input_json TEXT,status TEXT NOT NULL DEFAULT 'queued',current_step INTEGER NOT NULL DEFAULT 0,error TEXT,started_at TEXT,finished_at TEXT,created_at TEXT NOT NULL DEFAULT(datetime('now')),FOREIGN KEY(workflow_id) REFERENCES workflow_definitions(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS ix_workflow_runs_status ON workflow_runs(status,created_at);
CREATE TABLE IF NOT EXISTS workflow_step_runs(id INTEGER PRIMARY KEY,run_id INTEGER NOT NULL,step_id INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'queued',input_json TEXT,output_json TEXT,error TEXT,started_at TEXT,finished_at TEXT,created_at TEXT NOT NULL DEFAULT(datetime('now')),FOREIGN KEY(run_id) REFERENCES workflow_runs(id) ON DELETE CASCADE,FOREIGN KEY(step_id) REFERENCES workflow_steps(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS workflow_approvals(id INTEGER PRIMARY KEY,run_id INTEGER NOT NULL,step_id INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'pending',reason TEXT,requested_at TEXT NOT NULL DEFAULT(datetime('now')),decided_at TEXT,decided_by TEXT,decision_note TEXT,UNIQUE(run_id,step_id),FOREIGN KEY(run_id) REFERENCES workflow_runs(id) ON DELETE CASCADE);
`);
seed();}
function seed(){
 const defs=[
 ["new_document","Yeni Evrak İş Akışı","UYAP yeni evrakını sınıflandırır ve iş radarına işler.","event",{}],
 ["postal_watch","PTT / Tebligat Takibi","Bekleyen fiziki tebligatları sağlayıcı kuyruğuna hazırlar.","schedule",{minutes:120}],
 ["correspondence_watch","Müzekkere Radarı","Açık müzekkereleri yaşlandırır ve gecikenleri iş radarına taşır.","schedule",{minutes:360}],
 ["office_maintenance","BONO Bakım","Belge tarama, arşiv tarama, arama indeksi ve yedekleme işlerini sıraya alır.","schedule",{minutes:60}]
 ];
 const ins=db.prepare("INSERT OR IGNORE INTO workflow_definitions(key,name,description,trigger_type,trigger_config_json) VALUES(?,?,?,?,?)");
 for(const d of defs)ins.run(d[0],d[1],d[2],d[3],JSON.stringify(d[4]));
 const stepIns=db.prepare("INSERT OR IGNORE INTO workflow_steps(workflow_id,step_order,step_key,step_type,config_json,requires_approval,on_error) VALUES(?,?,?,?,?,?,?)");
 const id=k=>one("SELECT id FROM workflow_definitions WHERE key=?",k).id;
 stepIns.run(id("new_document"),1,"process_document","process_remote_document","{}",0,"stop");
 stepIns.run(id("postal_watch"),1,"queue_ptt","queue_ptt_checks","{}",0,"continue");
 stepIns.run(id("correspondence_watch"),1,"age_correspondence","age_correspondence","{\"warnDays\":14}",0,"continue");
 stepIns.run(id("office_maintenance"),1,"scan_documents","enqueue_job","{\"jobType\":\"scan_documents\",\"priority\":70}",0,"continue");
 stepIns.run(id("office_maintenance"),2,"scan_archive","enqueue_job","{\"jobType\":\"scan_case_archive\",\"priority\":80}",0,"continue");
 stepIns.run(id("office_maintenance"),3,"rebuild_search","enqueue_job","{\"jobType\":\"rebuild_search\",\"priority\":90}",0,"continue");
 stepIns.run(id("office_maintenance"),4,"backup","enqueue_job","{\"jobType\":\"backup_db\",\"priority\":20}",0,"continue");
}
function definitions(){return all(`SELECT w.*,COUNT(s.id) step_count,(SELECT COUNT(*) FROM workflow_runs r WHERE r.workflow_id=w.id AND r.status IN ('queued','running','waiting_approval')) active_runs,(SELECT MAX(created_at) FROM workflow_runs r WHERE r.workflow_id=w.id) last_run_at FROM workflow_definitions w LEFT JOIN workflow_steps s ON s.workflow_id=w.id GROUP BY w.id ORDER BY w.id`).map(x=>({...x,trigger_config:parse(x.trigger_config_json)}))}
function detail(id){const w=one("SELECT * FROM workflow_definitions WHERE id=?",id);if(!w)return null;return {...w,trigger_config:parse(w.trigger_config_json),steps:all("SELECT * FROM workflow_steps WHERE workflow_id=? ORDER BY step_order",id).map(s=>({...s,config:parse(s.config_json)})),runs:all("SELECT * FROM workflow_runs WHERE workflow_id=? ORDER BY id DESC LIMIT 30",id)}}
function trigger(key,input={},ref=null,type="manual"){const w=one("SELECT * FROM workflow_definitions WHERE key=? AND enabled=1",key);if(!w)throw new Error("Workflow kapalı veya bulunamadı: "+key);const r=db.prepare("INSERT INTO workflow_runs(workflow_id,trigger_type,trigger_ref,input_json,status) VALUES(?,?,?,?,?)").run(w.id,type,ref,JSON.stringify(input),"queued");const id=Number(r.lastInsertRowid);jobs.enqueue("run_workflow",{runId:id},"workflow-run:"+id,50);audit("workflow_triggered","workflow_run",id,{key,ref,type});return one("SELECT * FROM workflow_runs WHERE id=?",id)}
function dueSchedules(now=new Date()){const out=[];for(const w of all("SELECT * FROM workflow_definitions WHERE enabled=1 AND trigger_type='schedule'")){const c=parse(w.trigger_config_json),mins=Math.max(1,Number(c.minutes||60)),last=one("SELECT created_at FROM workflow_runs WHERE workflow_id=? ORDER BY id DESC LIMIT 1",w.id);if(!last||Date.now()-new Date(last.created_at+"Z").getTime()>=mins*60000)out.push(trigger(w.key,{scheduledAt:now.toISOString()},"schedule:"+now.toISOString().slice(0,13),"schedule"))}return out}
function executeStep(step,input){
 const c=parse(step.config_json);
 if(step.step_type==="enqueue_job"){const fp="wf:"+step.id+":"+new Date().toISOString().slice(0,13);return {jobId:jobs.enqueue(c.jobType,c.payload||{},fp,c.priority||100)}}
 if(step.step_type==="process_remote_document"){const v06=require("./v06");if(!input.remoteDocumentId)throw new Error("remoteDocumentId gerekli");return v06.processRemoteDocument(Number(input.remoteDocumentId),{text:input.text||""})}
 if(step.step_type==="queue_ptt_checks"){const rows=all("SELECT id,barcode FROM postal_shipments WHERE barcode IS NOT NULL AND status IN ('pending','in_transit','provider_error') AND (next_check_at IS NULL OR next_check_at<=datetime('now')) LIMIT 100");for(const p of rows)db.prepare("UPDATE postal_shipments SET next_check_at=datetime('now','+2 hours') WHERE id=?").run(p.id);return {queued:rows.length,shipmentIds:rows.map(x=>x.id),provider:"adapter_ready"}}
 if(step.step_type==="age_correspondence"){const days=Number(c.warnDays||14);const rows=all(`SELECT id,office_file_id,case_id,institution,subject,requested_at,sent_at FROM correspondence_tracking WHERE status NOT IN ('answered','closed') AND julianday('now')-julianday(COALESCE(sent_at,requested_at,created_at))>=? LIMIT 200`,days);const v06=require("./v06");for(const x of rows){db.prepare(`INSERT INTO work_radar_items(office_file_id,case_id,item_type,title,detail,severity,status,source_entity_type,source_entity_id,fingerprint,metadata_json) VALUES(?,?,?,?,?,'warning','open','correspondence',?,?,?) ON CONFLICT(fingerprint) DO UPDATE SET detail=excluded.detail,severity=excluded.severity`).run(x.office_file_id,x.case_id,"correspondence_wait","Müzekkere cevabı bekleniyor",[x.institution,x.subject].filter(Boolean).join(" · "),String(x.id),"corr-wait:"+x.id,JSON.stringify({warnDays:days}))}return {aged:rows.length}}
 throw new Error("Bilinmeyen workflow step: "+step.step_type);
}
function run(runId){const r=one("SELECT * FROM workflow_runs WHERE id=?",runId);if(!r)throw new Error("Workflow run bulunamadı");if(["completed","failed","cancelled"].includes(r.status))return r;const input=parse(r.input_json);db.prepare("UPDATE workflow_runs SET status='running',started_at=COALESCE(started_at,datetime('now')) WHERE id=?").run(runId);const steps=all("SELECT * FROM workflow_steps WHERE workflow_id=? AND step_order>? ORDER BY step_order",r.workflow_id,r.current_step);
 for(const s of steps){if(s.requires_approval){const a=one("SELECT * FROM workflow_approvals WHERE run_id=? AND step_id=?",runId,s.id);if(!a||a.status==="pending"){db.prepare("INSERT OR IGNORE INTO workflow_approvals(run_id,step_id,reason) VALUES(?,?,?)").run(runId,s.id,"Bu adım insan onayı gerektiriyor.");db.prepare("UPDATE workflow_runs SET status='waiting_approval' WHERE id=?").run(runId);return one("SELECT * FROM workflow_runs WHERE id=?",runId)}if(a.status!=="approved")throw new Error("Workflow adımı reddedildi")}
 const sr=Number(db.prepare("INSERT INTO workflow_step_runs(run_id,step_id,status,input_json,started_at) VALUES(?,?, 'running',?,datetime('now'))").run(runId,s.id,JSON.stringify(input)).lastInsertRowid);
 try{const out=executeStep(s,input);db.prepare("UPDATE workflow_step_runs SET status='completed',output_json=?,finished_at=datetime('now') WHERE id=?").run(JSON.stringify(out),sr);db.prepare("UPDATE workflow_runs SET current_step=? WHERE id=?").run(s.step_order,runId)}
 catch(e){db.prepare("UPDATE workflow_step_runs SET status='failed',error=?,finished_at=datetime('now') WHERE id=?").run(String(e.stack||e),sr);if(s.on_error!=="continue"){db.prepare("UPDATE workflow_runs SET status='failed',error=?,finished_at=datetime('now') WHERE id=?").run(String(e.stack||e),runId);throw e}}
 }
 db.prepare("UPDATE workflow_runs SET status='completed',finished_at=datetime('now') WHERE id=?").run(runId);audit("workflow_completed","workflow_run",runId,{});return one("SELECT * FROM workflow_runs WHERE id=?",runId)}
function approve(id,approved,note=""){const a=one("SELECT * FROM workflow_approvals WHERE id=?",id);if(!a)throw new Error("Onay bulunamadı");db.prepare("UPDATE workflow_approvals SET status=?,decided_at=datetime('now'),decided_by='lawyer',decision_note=? WHERE id=?").run(approved?"approved":"rejected",note,id);if(approved){db.prepare("UPDATE workflow_runs SET status='queued' WHERE id=?").run(a.run_id);jobs.enqueue("run_workflow",{runId:a.run_id},"workflow-resume:"+a.run_id+":"+id,40)}else db.prepare("UPDATE workflow_runs SET status='cancelled',finished_at=datetime('now') WHERE id=?").run(a.run_id);audit("workflow_approval","workflow_approval",id,{approved,note});return one("SELECT * FROM workflow_approvals WHERE id=?",id)}
function runs(limit=100){return all(`SELECT r.*,w.key workflow_key,w.name workflow_name FROM workflow_runs r JOIN workflow_definitions w ON w.id=r.workflow_id ORDER BY r.id DESC LIMIT ?`,limit)}
function approvals(){return all(`SELECT a.*,w.name workflow_name,s.step_key FROM workflow_approvals a JOIN workflow_runs r ON r.id=a.run_id JOIN workflow_definitions w ON w.id=r.workflow_id JOIN workflow_steps s ON s.id=a.step_id WHERE a.status='pending' ORDER BY a.id DESC`)}
init();module.exports={init,definitions,detail,trigger,dueSchedules,run,approve,runs,approvals};