const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const src=fs.readFileSync('web/js/views/active/uyap.js','utf8');
const userQueries=fs.readFileSync('web/js/views/active/user-queries.js','utf8');
new vm.Script(src.replace(/^import .*;\s*$/gm,'').replace(/export async function renderUyap/,'async function renderUyap'),{filename:'uyap.js'});
new vm.Script(userQueries.replace(/^import .*;\s*$/gm,''),{filename:'user-queries.js'});
assert.match(src,/UYAP'ta Sorgula/);
assert.match(src,/mountUserQueries\(id,/);
assert.match(userQueries,/\/query-support/);
assert.match(userQueries,/\/query'/);
assert.match(userQueries,/X-Bono-User-Action/);
assert.match(userQueries,/query-history/);
assert.match(userQueries,/Yeniden sorgula/);
assert.match(src,/PDF\/UDF dosyalarını indirmez|Fiziksel evrak indirme ayrı onaydır/);
assert.match(src,/r\.party_names/);
assert.match(src,/file\.party_names/);
assert.match(src,/file\.client_name/);
assert.match(src,/inventoryState\(file,docs\)/);
assert.match(src,/inventoryTotals\(rows\)/);
assert.match(src,/Dosya Envanteri \/ Kanıt Durumu/);
assert.match(src,/filterProvince/);
assert.match(src,/filterDistrict/);
assert.match(src,/targetedSearchForm\(searchOptions\)/);
assert.match(src,/Soruşturma numarasını bilmiyor musun/);
assert.match(src,/api\.caseDocumentView\(caseId,docId\)/);
assert.match(src,/api\.caseDocumentContentUrl\(caseId,docId\)/);
assert.match(src,/integrity\.verified===true/);
assert.match(src,/viewer\.openable===true/);
assert.doesNotMatch(src,/href="\\\/api\\\/assets/);
assert.match(userQueries,/approved-downloads/);
assert.match(userQueries,/İndirme askısını kaldır/);
const css=fs.readFileSync('web/styles-active.css','utf8');
for(const x of [/\.case-sync-panel/,/\.case-parties/,/\.case-document-summary/,/\.case-download-controls/,/\.case-document-viewer/,/\.case-document-pdf/,/\.case-targeted-search/])assert.match(css,x);
console.log('PASS case UI: controlled single-case query, inventory evidence, parties, explicit downloads, secure viewer');

const handoff=fs.readFileSync('web/js/views/active/cbs-case-handoff.js','utf8');
new vm.Script(handoff.replace(/^export /gm,''),{filename:'cbs-case-handoff.js'});
assert.match(src,/mountCbsCaseHandoff\(api,cbsSchema\)/);
assert.match(src,/api\.uyapCbsPartySearchSchema\(\)/);
assert.match(handoff,/api\.uyapCbsUnits\(Number\(province\.element\.value\)\)/);
assert.match(handoff,/api\.searchUyapCbsParty\(\{/);
assert.match(handoff,/api\.uyapCbsPartySearchStatus\(reply\.searchId\)/);
assert.match(handoff,/uyap\.targeted-cbs-party-search\.v1/);
assert.match(handoff,/maxCandidates:25/);
assert.match(handoff,/days>120/);
assert.match(handoff,/api\.uyapCases\(\)/);
assert.match(handoff,/setTimeout\(check,5000\)/);
assert.doesNotMatch(handoff,/Efe Lefer|api\.syncUyapDocuments|download-missing|queueMissingUyapDocuments/);
assert.match(css,/\.case-cbs-handoff-panel/);
console.log('PASS CBS case handoff: observed-contract discovery, bounded candidates, no download or hardcoded client');
