'use strict';
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{spawnSync,spawn}=require('node:child_process'),net=require('node:net');
const {build}=require('./build_observation_package'),{operate,inspect,hash}=require('./package_operations'),{DatabaseSync}=require('node:sqlite');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'bono-go-ready-')),target=path.join(tmp,'target'),bundle=path.join(tmp,'bundle'),results=[];
const pass=name=>{results.push(name);console.log('PASS '+name)},port=()=>new Promise(resolve=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>resolve(p));});});
fs.mkdirSync(path.join(target,'bridge'),{recursive:true});const original='// synthetic local change\nmodule.exports={preserved:true};';fs.writeFileSync(path.join(target,'bridge/server.js'),original);
const manifest=build(target,bundle);assert.equal(manifest.files.length,13);assert.equal(fs.readFileSync(path.join(bundle,'rollback/bridge/server.js'),'utf8'),original);
let completed=false;process.once('beforeExit',()=>{if(!completed){console.error('TEST_INCOMPLETE');process.exitCode=1;}});
const watchdog=setTimeout(()=>{console.error('TEST_TIMEOUT');process.exit(1);},30000);
const cli=(file,args,options={})=>spawn(process.execPath,[path.join(bundle,file),...args],{stdio:['pipe','pipe','pipe'],...options});
const awaitExit=cp=>new Promise(resolve=>cp.once('exit',(code)=>resolve(code)));
(async()=>{
 const p=await port();assert.equal((await operate(bundle,target,'Verify',p)).state,'original');pass('verify_read_only_preimages');
 const listener=net.createServer();await new Promise(r=>listener.listen(p,'127.0.0.1',r));await assert.rejects(operate(bundle,target,'Apply',p));listener.close();assert.equal(inspect(bundle,target).state,'original');pass('occupied_port_rejected_before_changes');
 await assert.rejects(operate(bundle,target,'Apply',p,{afterFile:n=>{if(n===3)throw Error('synthetic_interrupt');}}));assert.equal(inspect(bundle,target).state,'partial');pass('interrupted_multi_file_install_observable');
 assert.equal((await operate(bundle,target,'Apply',p)).state,'installed');assert.equal((await operate(bundle,target,'Apply',p)).state,'installed');pass('resume_apply_and_idempotent_apply');
 assert.equal((await operate(bundle,target,'Rollback',p)).state,'original');assert.equal((await operate(bundle,target,'Rollback',p)).state,'original');pass('exact_idempotent_rollback');
 await operate(bundle,target,'Apply',p);fs.writeFileSync(path.join(target,'bridge/server.js'),'TRUNCATED');await assert.rejects(operate(bundle,target,'Rollback',p));assert.equal((await operate(bundle,target,'Recover',p)).state,'original');assert.equal(fs.readFileSync(path.join(target,'bridge/server.js'),'utf8'),original);assert(fs.existsSync(path.join(target,'.bono-observation-recovery')));pass('damaged_file_requires_explicit_recover_and_is_preserved');
 await operate(bundle,target,'Apply',p);const source=path.join(tmp,'source.db'),evidence=path.join(tmp,'evidence.db');const db=new DatabaseSync(source);db.exec("CREATE TABLE cases(court_file_no TEXT,uyap_birim_id TEXT,uyap_dosya_id TEXT);CREATE TABLE uyap_command_queue(status TEXT);INSERT INTO uyap_command_queue VALUES('running');CREATE TABLE app_settings(key TEXT,value TEXT);INSERT INTO app_settings VALUES('uyap_manual_download_pause','1');");db.close();const before=hash(source);
 const normal=spawnSync(process.execPath,[path.join(target,'bridge/server.js')],{encoding:'utf8',env:{...process.env,BONO_OBSERVATION_ONLY:'0'}});assert.notEqual(normal.status,0);assert.equal(hash(source),before);pass('normal_core_blocked_until_rollback');
 const child=cli('launch_observation.js',[bundle,target,source,evidence,'a'.repeat(32),String(p)]);let logs='',errors='';child.stdout.on('data',b=>logs+=b);child.stderr.on('data',b=>errors+=b);
 const exited=awaitExit(child);let ready;for(let i=0;i<120;i++){if(logs.includes('"state":"ready"')){ready=JSON.parse(logs.trim().split('\n')[0]);break;}await new Promise(r=>setTimeout(r,50));}assert(ready,errors);assert.equal(ready.buildId,manifest.buildId);pass('real_launcher_mode_build_pid_readiness');
 const p2=await port(),evidence2=path.join(tmp,'second.db');const second=cli('launch_observation.js',[bundle,target,source,evidence2,'a'.repeat(32),String(p2)]);assert.notEqual(await awaitExit(second),0);assert(!fs.existsSync(evidence2));pass('same_source_second_observer_other_port_rejected');
 child.stdin.end('stop\n');assert.equal(await exited,0);assert(!fs.existsSync(source+'.bono-observer.lock'));assert.equal(hash(source),before);pass('graceful_stop_releases_lease_source_queue_pause_unchanged');
 const missing=cli('launch_observation.js',[bundle,target,path.join(tmp,'missing.db'),path.join(tmp,'missing-evidence.db'),'a'.repeat(32),String(p)]);assert.notEqual(await awaitExit(missing),0);assert(!fs.existsSync(path.join(tmp,'missing-evidence.db')));pass('missing_source_error_propagated');
 const occupied=net.createServer(socket=>socket.destroy());await new Promise(r=>occupied.listen(p,'127.0.0.1',r));const bound=cli('launch_observation.js',[bundle,target,source,path.join(tmp,'bind-failure.db'),'a'.repeat(32),String(p)]);assert.notEqual(await awaitExit(bound),0);assert(!fs.existsSync(path.join(tmp,'bind-failure.db')));assert(!fs.existsSync(source+'.bono-observer.lock'));await new Promise(r=>occupied.close(r));pass('bind_failure_creates_no_evidence_and_releases_lease');
 // Exercise original PowerShell wrappers with a mocked EMPTY process inventory only inside this synthetic test.
 // This does not bypass production checks: the exact production wrapper is executed and explicit inventory results are supplied by the fixture.
 const fake=path.join(tmp,'exit17.cmd');fs.writeFileSync(fake,'@exit /b 17\r\n');const quote=s=>"'"+s.replaceAll("'","''")+"'";
 const command="function Get-CimInstance { @() }; $env:BONO_DB_PATH='SYNTHETIC_PARENT'; & "+quote(path.join(bundle,'launch_observation.ps1'))+' -TargetRoot '+quote(target)+' -NodeExe '+quote(fake)+' -SourceDB '+quote(source)+' -EvidenceDB '+quote(path.join(tmp,'fake-evidence.db'))+' -ExtensionId '+quote('a'.repeat(32))+" -CorePort "+p+"; Write-Output ('restored=' + ($env:BONO_DB_PATH -eq 'SYNTHETIC_PARENT')); exit $LASTEXITCODE";
 const failed=spawnSync('powershell',['-NoProfile','-Command',command],{encoding:'utf8'});assert.equal(failed.status,17,failed.stdout+failed.stderr);assert(failed.stdout.includes('restored=True'));pass('exact_ps_launcher_native_exit17_and_environment_restore');
 const pscommand="function Get-CimInstance { @() }; & "+quote(path.join(bundle,'observation_package.ps1'))+' -TargetRoot '+quote(target)+' -Mode Rollback -NodeExe '+quote(process.execPath)+' -CorePort '+p+'; exit $LASTEXITCODE';
 const rollback=spawnSync('powershell',['-NoProfile','-Command',pscommand],{encoding:'utf8'});assert.equal(rollback.status,0,rollback.stdout+rollback.stderr);assert.equal(fs.readFileSync(path.join(target,'bridge/server.js'),'utf8'),original);pass('exact_ps_rollback_with_fixture_inventory');
 const blockedCommand=pscommand.replace('function Get-CimInstance { @() }',"function Get-CimInstance { [pscustomobject]@{Name='node.exe';CommandLine='node bridge/server.js'} }");const blocked=spawnSync('powershell',['-NoProfile','-Command',blockedCommand],{encoding:'utf8'});assert.notEqual(blocked.status,0);assert.equal(inspect(bundle,target).state,'original');pass('ps_inventory_running_core_blocks_mutation');
 // Env is passed only to the child; neither PS nor JS launcher sets parent values.
 const envBefore=JSON.stringify(process.env);const invalid=cli('launch_observation.js',[bundle,target,source,path.join(tmp,'invalid.db'),'a'.repeat(32),String(p)]);assert.notEqual(await awaitExit(invalid),0);assert.equal(JSON.stringify(process.env),envBefore);pass('parent_environment_preserved_on_failure');
 const lease=require('../bridge/observation_lease');const owned=lease.acquire(source);assert.throws(()=>lease.recover(source),/alive/);owned.release();pass('alive_lease_never_removed');
 const stale=spawnSync(process.execPath,['-e','process.exit(0)']);fs.writeFileSync(source+'.bono-observer.lock',JSON.stringify({pid:stale.pid,token:'dead-fixture'}));lease.recover(source);assert(!fs.existsSync(source+'.bono-observer.lock'));pass('explicit_dead_lease_recovery');
 await operate(bundle,target,'Apply',p);fs.unlinkSync(path.join(target,'bridge/server.js'));assert.equal((await operate(bundle,target,'Recover',p)).state,'original');pass('missing_original_file_recovered');
 const opLock=path.join(target,'.bono-package.lock');fs.writeFileSync(opLock,JSON.stringify({pid:process.pid,buildId:manifest.buildId}));await assert.rejects(operate(bundle,target,'Recover',p));assert(fs.existsSync(opLock));fs.unlinkSync(opLock);fs.writeFileSync(opLock,JSON.stringify({pid:stale.pid,buildId:manifest.buildId}));assert.equal((await operate(bundle,target,'Recover',p)).state,'original');pass('active_operation_lock_preserved_dead_lock_explicit_recovery');
 const payload=path.join(bundle,'payload/extension/content.js'),saved=fs.readFileSync(payload);fs.appendFileSync(payload,'tamper');assert.throws(()=>inspect(bundle,target),/hash/);fs.writeFileSync(payload,saved);pass('tampered_bundle_rejected');
 completed=true;console.log(JSON.stringify({ok:true,results,buildId:manifest.buildId}));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>clearTimeout(watchdog));
