'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'bono-user-queries-'));process.env.BONO_DB_PATH=path.join(tmp,'source.db');process.env.USERPROFILE=tmp;
const db=require('../bridge/db'),uyap=require('../bridge/uyap'),policy=require('../bridge/uyap_user_queries');
const set=(k,v)=>db.prepare('INSERT OR REPLACE INTO app_settings(key,value) VALUES(?,?)').run(k,String(v));
set('uyap_integration_mode','browser_readonly');set('uyap_manual_download_pause','1');set('uyap_session_state','ready');
db.exec("INSERT INTO cases(id,court,court_file_no,uyap_birim_id,uyap_dosya_id) VALUES(1,'Fixture Hukuk Mahkemesi','2020/1','unit1','PRIVATE_FILE'),(93,'Fixture CBS','2020/93','unit2','PRIVATE_CBS');INSERT INTO uyap_endpoints(endpoint_key,method,host,path,enabled) VALUES('document.list','POST','avukat.uyap.gov.tr','/list_dosya_evraklar.ajx',1),('document.pdf','GET','vatandas.uyap.gov.tr','/view_document_brd.uyap',1);");
db.prepare("INSERT INTO uyap_endpoints(endpoint_key,method,host,path,enabled) VALUES('case.search','POST','avukat.uyap.gov.tr','/avukat_mahkemeleri_sorgula.ajx',1)").run();
for(let i=0;i<270;i++)db.prepare("INSERT INTO uyap_command_queue(command_type,endpoint_key,payload_json) VALUES('fetch_json','case.search',?)").run(JSON.stringify({token:'PRIVATE_TOKEN',context:{caseId:1},name:'PRIVATE_PERSON'}));
const ids=db.prepare('SELECT id FROM uyap_command_queue ORDER BY id').all().map(x=>x.id),manifest={schema:1,verified:true,queueIdDigest:policy.digest(ids)};
assert.throws(()=>policy.migrate(db,{expectedQueued:270,backupManifest:manifest,afterRow:n=>{if(n===100)throw Error('synthetic_interruption');}}),/interruption/);
assert.equal(db.prepare("SELECT count(*) n FROM uyap_command_queue WHERE status='queued'").get().n,270);
assert.equal(db.prepare("SELECT count(*) n FROM sqlite_master WHERE name='uyap_query_history'").get().n,0);
assert.equal(policy.migrate(db,{expectedQueued:270,backupManifest:manifest}).retired,270);assert(policy.migrate(db,{expectedQueued:270,backupManifest:manifest}).alreadyApplied);
assert.throws(()=>db.prepare("UPDATE uyap_command_queue SET status='queued' WHERE id=1").run(),/retired/);assert.throws(()=>db.prepare('DELETE FROM uyap_command_queue WHERE id=1').run(),/retired/);
const service=policy.install(db,uyap);assert.equal(uyap.claimNext('avukat.uyap.gov.tr','query'),null);
assert.equal(uyap.reportResult(1,{ok:true,status:200,data:{}}).reason,'inactive_user_command');
assert.throws(()=>uyap.enqueueCaseDocumentSync(1),/explicit/);
assert(!service.status(93).supported);assert(!service.status(1).supported);
policy.certifyBinding(db,{kind:'verified_portal_binding',caseId:1,unitId:'unit1',caseNo:'2020/1',dosyaId:'PRIVATE_FILE',evidenceRef:'observation:'+crypto.randomUUID(),adapter:'court_documents_v1'});
const key=crypto.randomUUID(),one=service.begin(1,{requestKey:key});assert.equal(service.begin(1,{requestKey:key}).commandId,one.commandId);assert.equal(service.begin(1,{requestKey:crypto.randomUUID(),refresh:true}).commandId,one.commandId);
const cmd=uyap.claimNext('avukat.uyap.gov.tr','query');assert.equal(cmd.id,one.commandId);assert.equal(uyap.sessionState().manualDownloadPaused,true);
uyap.reportResult(cmd.id,{ok:true,status:200,contentType:'application/json',data:{tumEvraklar:[{evrakId:'PRIVATE_DOC',dosyaId:'PRIVATE_FILE',tur:'Dava Dilekçesi',onaylandigiTarih:'01/01/2020'}]}});
assert.equal(service.history(1)[0].state,'completed');assert.equal(service.begin(1,{requestKey:crypto.randomUUID()}).state,'cache_hit');
const remote=service.downloadOptions(1)[0].id;
assert.throws(()=>service.beginDownloads(1,{requestKey:crypto.randomUUID(),documentIds:[remote]}),/explicit/);
const downloadKey=crypto.randomUUID(),download=service.beginDownloads(1,{requestKey:downloadKey,documentIds:[remote],confirmed:true});assert.equal(download.commandIds.length,1);assert.equal(service.beginDownloads(1,{requestKey:downloadKey,documentIds:[remote],confirmed:true}).commandIds[0],download.commandIds[0]);
assert.equal(uyap.claimNext('vatandas.uyap.gov.tr','download'),null);assert.equal(uyap.sessionState().manualDownloadPaused,true);
const fill=db.prepare("INSERT INTO uyap_command_queue(command_type,endpoint_key,payload_json) VALUES('fetch_json','case.search','{}')");const fills=[];for(let i=0;i<199;i++)fills.push(Number(fill.run().lastInsertRowid));
assert.throws(()=>service.begin(1,{requestKey:crypto.randomUUID(),refresh:true}),/active_command_limit/);for(const id of fills)db.prepare('DELETE FROM uyap_command_queue WHERE id=?').run(id);
const fresh=service.begin(1,{requestKey:crypto.randomUUID(),refresh:true});assert.notEqual(fresh.commandId,one.commandId);
// Force only the synthetic scheduler clock forward without waiting; rate tests separately verify real spacing.
db.prepare('UPDATE uyap_rate_state SET next_allowed_ms=0').run();const freshCmd=uyap.claimNext('avukat.uyap.gov.tr','any');assert.equal(freshCmd.id,fresh.commandId);
uyap.reportResult(freshCmd.id,{ok:true,status:200,data:{errorCode:'PRTL_GNL_1-1',error:'PRIVATE_AUTH_MESSAGE'}});assert.equal(service.history(1)[0].state,'failed');
assert(!JSON.stringify(service.history(1)).includes('PRIVATE_'));
assert.throws(()=>db.prepare("UPDATE uyap_query_events SET state='completed'").run(),/immutable/);
const third=service.begin(1,{requestKey:crypto.randomUUID(),refresh:true});db.prepare("UPDATE uyap_command_queue SET status='running',attempts=1,dispatched_at=datetime('now','-10 minutes') WHERE id=?").run(third.commandId);uyap.claimNext('avukat.uyap.gov.tr','query');assert.equal(service.history(1)[0].state,'execution_unknown');assert.equal(uyap.reportResult(third.commandId,{ok:true,status:200,data:{tumEvraklar:[]}}).reason,'inactive_user_command');
const fourth=service.begin(1,{requestKey:crypto.randomUUID(),refresh:true});db.prepare("UPDATE cases SET uyap_dosya_id='CHANGED' WHERE id=1").run();uyap.claimNext('avukat.uyap.gov.tr','query');assert.equal(db.prepare('SELECT status FROM uyap_command_queue WHERE id=?').get(fourth.commandId).status,'failed');
db.prepare("UPDATE cases SET uyap_dosya_id='PRIVATE_FILE' WHERE id=1").run();
const tamper=service.begin(1,{requestKey:crypto.randomUUID(),refresh:true});db.prepare("UPDATE uyap_command_queue SET payload_json='{}' WHERE id=?").run(tamper.commandId);uyap.claimNext('avukat.uyap.gov.tr','query');assert.equal(db.prepare('SELECT status FROM uyap_command_queue WHERE id=?').get(tamper.commandId).status,'failed');
db.prepare("UPDATE uyap_endpoints SET path='/avukat_mahkemeleri_sorgula.ajx' WHERE endpoint_key='document.list'").run();assert.throws(()=>service.begin(1,{requestKey:crypto.randomUUID(),refresh:true}),/explicit_supported/);db.prepare("UPDATE uyap_endpoints SET path='/list_dosya_evraklar.ajx' WHERE endpoint_key='document.list'").run();
assert.throws(()=>policy.migrate(db,{expectedQueued:270,backupManifest:{...manifest,queueIdDigest:'wrong'}}),/reconciliation/);
policy.rollbackHold(db);assert.equal(uyap.claimNext('avukat.uyap.gov.tr').reason,'migration_required');assert.equal(db.prepare("SELECT count(*) n FROM uyap_command_queue WHERE status='archived'").get().n,270);
db.close();console.log(JSON.stringify({ok:true,tests:['270_retired_and_mapped','transaction_interruption_atomic','idempotent_migration','immutable_history_and_tombstones','late_legacy_result_rejected','automatic_producers_blocked','CBS_unverified','binding_required','user_key_dedup','same_case_active_dedup','explicit_download_selection_and_dedup','active_200_limit','query_while_download_paused','valid_cache_no_enqueue','explicit_refresh','HTTP200_denial_not_success','history_privacy','stale_execution_not_retried','changed_binding_blocks_claim','payload_mutation_blocks_claim','endpoint_alias_cannot_expand_scope','idempotency_reconciles_original_ids','rollback_retains_archive_and_holds'],networkRequests:0}));
