'use strict';
const assert=require('node:assert/strict'),{randomUUID}=require('node:crypto'),create=require('../bridge/uyap_session_check');
let time=100,success=0,denials=0,enabled=true,count=0;
const check=create({available:()=>enabled,verified:()=>success++,denied:()=>denials++,now:()=>time});
const test=(name,fn)=>{fn();count++;console.log('PASS '+name)};
const ctx={tabId:7,frameId:0,documentId:randomUUID(),buildId:'fixture-build'};
const begin=()=>check.begin(randomUUID());
test('startup has no implicit check',()=>assert.equal(check.status().state,'not_started'));
test('explicit key required',()=>assert.throws(()=>check.begin('invalid')));
let s=begin();
test('double click and parallel start share one pending operation',()=>assert.equal(begin().id,s.id));
test('foreign subframe cannot claim',()=>assert.throws(()=>check.claim({...ctx,id:s.id,frameId:1})));
let claim=check.claim({...ctx,id:s.id});
test('second tab cannot claim same check',()=>assert.throws(()=>check.claim({...ctx,id:s.id,tabId:8})));
test('wrong page result rejected',()=>assert.throws(()=>check.result({...claim,documentId:randomUUID(),status:200,validJson:true,applicationError:false})));
test('wrong build result rejected',()=>assert.throws(()=>check.result({...claim,buildId:'old',status:200,validJson:true,applicationError:false})));
test('HTTP200 application denial does not recover session',()=>{assert.equal(check.result({...claim,status:200,validJson:true,applicationError:true}).reason,'application_denied');assert.equal(success,0)});
s=begin();claim=check.claim({...ctx,id:s.id});
test('HTTP401 marks login required',()=>{assert.equal(check.result({...claim,status:401,validJson:false,applicationError:false}).reason,'login_required');assert.equal(denials,1)});
s=begin();claim=check.claim({...ctx,id:s.id});
test('HTML or invalid JSON cannot recover',()=>assert.equal(check.result({...claim,status:200,validJson:false,applicationError:false}).state,'blocked'));
s=begin();claim=check.claim({...ctx,id:s.id});time+=30001;
test('late result expires without recovery',()=>{assert.throws(()=>check.result({...claim,status:200,validJson:true,applicationError:false}));assert.equal(success,0)});
s=begin();claim=check.claim({...ctx,id:s.id});
test('only matching successful check recovers',()=>{assert.equal(check.result({...claim,status:200,validJson:true,applicationError:false}).state,'ready');assert.equal(success,1)});
test('duplicate result cannot recover twice',()=>assert.throws(()=>check.result({...claim,status:200,validJson:true,applicationError:false})));
test('hold or observer availability blocks new check',()=>{enabled=false;assert.throws(begin)});
test('Core restart discards session check authorization',()=>assert.equal(create({available:()=>true,verified:()=>{}}).status().state,'not_started'));
console.log(JSON.stringify({ok:true,tests:count,portalRequests:0,queueAccess:0}));
