const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const src=fs.readFileSync('web/js/views/active/uyap.js','utf8');
new vm.Script(src.replace(/^import .*;\s*$/gm,'').replace(/export async function renderUyap/,'async function renderUyap'),{filename:'uyap.js'});
assert.match(src,/UYAP'tan Evrak Listesini Getir/);
assert.match(src,/api\.syncUyapDocuments\(caseId\)/);
assert.match(src,/Bu işlem PDF\/UDF dosyalarını indirmez/);
assert.match(src,/result\.commandId/);
assert.match(src,/r\.party_names/);
assert.match(src,/file\.party_names/);
assert.match(src,/file\.client_name/);
assert.match(src,/filterProvince/);
assert.match(src,/filterDistrict/);
assert.match(src,/caseProvince\(r\)/);
assert.match(src,/Bu filtreler yalnızca BONO'da kayıtlı dosyaları gösterir/);
assert.match(src,/targetedSearchForm\(searchOptions\)/);
assert.match(src,/api\.uyapCaseSearchOptions\(\)/);
assert.match(src,/api\.searchUyapCase\(/);
assert.match(src,/api\.uyapCaseSearchStatus\(searchId\)/);
assert.match(src,/searchOptions\?\?null|searchOptions\)/);
assert.match(src,/Soruşturma numarasını bilmiyor musun/);
assert.match(src,/api\.startUyapDiscovery\(\{statuses:\[0,1\],syncDocuments:false\}\)/);
assert.doesNotMatch(src,/api\.startUyapArchive\(\)/);
assert.match(src,/case-document-summary/);
assert.match(src,/case-document-guidance/);
assert.match(src,/case-download-controls/);
assert.match(src,/İndirme durumu kontrol ediliyor/);
assert.match(src,/api\.queueMissingUyapDocuments\(caseId,count\)/);
assert.match(src,/api\.uyapDocumentSyncStatus\(caseId\)/);
assert.match(src,/api\.caseDocumentView\(caseId,docId\)/);
assert.match(src,/api\.caseDocumentContentUrl\(caseId,docId\)/);
assert.match(src,/integrity\.verified===true/);
assert.match(src,/viewer\.openable===true/);
assert.doesNotMatch(src,/href="\\\/api\\\/assets/);
assert.match(src,/api\.uyapDownloadSummary\(caseId\)/);
assert.match(src,/if\(!confirm\(/);
assert.match(src,/state==='completed'\|\|state==='empty'/);
assert.match(src,/uyap\.document-sync\.v1/);
assert.match(src,/x\.command\?\.id/);
assert.match(src,/x\.terminal/);
assert.match(src,/x\.success/);
assert.match(src,/x\.pollAfterMs/);
assert.match(src,/result\?\.accepted!==true/);
assert.match(src,/statusSupported=false/);
const css=fs.readFileSync('web/styles-active.css','utf8');
assert.match(css,/\.case-sync-panel/);
assert.match(css,/\.case-parties/);
assert.match(css,/\.case-document-summary/);
assert.match(css,/\.case-download-controls/);
assert.match(css,/\.case-document-viewer/);
assert.match(css,/\.case-document-pdf/);
assert.match(css,/\.case-targeted-search/);
console.log('PASS case UI: JS syntax, single-case list inquiry, no automatic download, source-grounded party fields, empty state style');
