'use strict';
const assert=require('node:assert/strict');
const {prepareCbsList:prepare,selectCbsTarget:select}=require('../bridge/uyap_cbs_list_adapter');
const observation={sourceType:'persisted live observation',reference:'synthetic-observation',method:'POST',path:'/avukat_dosya_sorgula_cbs_brd.ajx',request:{query:{},body:{dosyaDurumKod:0,pageSize:500,pageNumber:1,birimId:'',birimTuru2:'unit',birimTuru3:'3'}}};
// Synthetic fixtures exercise the contract; they certify no live identity or execution permission.
const unit={sourceType:'completed cbs.units',reference:'synthetic-unit',birimId:'unit',ilKodu:26};
const request=prepare({observation,unit}),target={birimId:'unit',dosyaNo:'2030/123'};
const row={birimId:'unit',dosyaNo:'2030/123',dosyaId:'synthetic-opaque',dosyaDurumKod:0};
const page=(data,context=request.context)=>({data,context,reference:'synthetic-result'});
let n=0;const test=(name,fn)=>{fn();n++;console.log('PASS',name);};
test('observed unit maps to birimTuru2; no party/year parameter',()=>{assert.equal(request.body.birimTuru2,'unit');assert.equal(request.body.birimId,'');assert.equal(request.executable,false);assert(!('dosyaNo' in request.body));});
test('requires existing evidence',()=>assert.throws(()=>prepare({observation:{},unit})));
test('rejects secret or unknown template fields',()=>assert.throws(()=>prepare({observation:{...observation,request:{body:{...observation.request.body,token:'secret'}}},unit})));
test('requires completed unit evidence',()=>assert.throws(()=>prepare({observation,unit:{...unit,reference:null}})));
test('exact target selected locally with opaque ID provenance',()=>{const r=select({target,pages:[page([[row],1])]});assert.equal(r.state,'found');assert.equal(r.identity.dosyaId,row.dosyaId);assert.equal(r.canBindDocuments,false);});
test('empty complete result',()=>assert.equal(select({target,pages:[page([[],0])]}).state,'not_found'));
test('other investigation excluded',()=>assert.equal(select({target,pages:[page([[{...row,dosyaNo:'2030/124'}],1])]}).state,'not_found'));
test('existing opaque ID mismatch stops',()=>assert.equal(select({target:{...target,dosyaId:'different'},pages:[page([[row],1])]}).state,'identity_mismatch'));
test('HTTP200 authority object rejected',()=>assert.throws(()=>select({target,pages:[page({error:'PRTL_GNL_1-1'})]})));
test('summary cannot replace response',()=>assert.throws(()=>select({target,pages:[page({type:'array',length:2})]})));
test('truncated page never proves absence or identity',()=>assert.equal(select({target,pages:[page([[row],2])]}).state,'incomplete'));
test('missing row identity rejected',()=>assert.throws(()=>select({target,pages:[page([[{...row,dosyaId:null}],1])]})));
test('foreign unit rejected',()=>assert.throws(()=>select({target,pages:[page([[{...row,birimId:'other'}],1])]})));
test('mixed status rejected',()=>assert.throws(()=>select({target,pages:[page([[{...row,dosyaDurumKod:1}],1])]})));
test('duplicate identity rejected',()=>assert.throws(()=>select({target,pages:[page([[row,row],2])]})));
test('same number with two IDs ambiguous',()=>assert.equal(select({target,pages:[page([[row,{...row,dosyaId:'second'}],2])]}).state,'ambiguous'));
test('page gap rejected',()=>assert.throws(()=>select({target,pages:[page([[row],1],{...request.context,page:2})]})));
test('complete two-page list selects exact target',()=>{const rows=Array.from({length:500},(_,i)=>({...row,dosyaNo:'2031/'+(i+1),dosyaId:'synthetic-'+i}));assert.equal(select({target,pages:[page([rows,501]),page([[row],501],{...request.context,page:2})]}).state,'found');});
test('changed total rejected',()=>{const rows=Array.from({length:500},(_,i)=>({...row,dosyaNo:'2031/'+(i+1),dosyaId:'synthetic-'+i}));assert.throws(()=>select({target,pages:[page([rows,501]),page([[row],502],{...request.context,page:2})]}));});
console.log(n+' tests PASS; no live I/O');
