"use strict";
const fs=require("node:fs");
const os=require("node:os");
const path=require("node:path");
const crypto=require("node:crypto");
function must(v,m){if(!v)throw new Error(m)}
const root=fs.mkdtempSync(path.join(os.tmpdir(),"bono-cbs-user-query-"));
process.env.BONO_DB_PATH=path.join(root,"fixture.db");
process.env.USERPROFILE=root;
const db=require("../bridge/db");
const uyap=require("../bridge/uyap");
const policy=require("../bridge/uyap_user_queries");
function setting(k,v){db.prepare("insert into app_settings(key,value) values(?,?) on conflict(key) do update set value=excluded.value").run(k,v)}
setting("uyap_integration_mode","browser_readonly");
setting("uyap_session_state","ready");
setting("uyap_manual_download_pause","1");
setting("uyap_manual_download_reason","fixture_pause");
setting("uyap_document_download_state","paused_manual");
db.prepare("insert or replace into uyap_endpoints(endpoint_key,method,host,path,purpose,enabled,min_interval_ms) values(?,?,?,?,?,?,?)").run("cbs.search","POST","avukat.uyap.gov.tr","/avukat_dosya_sorgula_cbs_brd.ajx","search",1,0);
db.prepare("insert or replace into uyap_endpoints(endpoint_key,method,host,path,purpose,enabled,min_interval_ms) values(?,?,?,?,?,?,?)").run("cbs.units","POST","avukat.uyap.gov.tr","/cbs_birim_sorgula.ajx","units",1,0);
const observed={query:{},body:{dosyaDurumKod:0,pageSize:500,pageNumber:1,birimId:"",birimTuru2:"OBSERVED-UNIT",birimTuru3:"3"},headers:{"Content-Type":"application/json"}};
db.prepare("insert into uyap_endpoint_observations(method,host,path,status,content_type,sample_keys_json,sample_request_json,last_seen_at,hit_count) values(?,?,?,?,?,?,?,datetime('now'),?)").run("POST","avukat.uyap.gov.tr","/avukat_dosya_sorgula_cbs_brd.ajx",200,"application/json","[]",JSON.stringify(observed),9);
db.prepare("insert into uyap_command_queue(command_type,endpoint_key,payload_json,status,result_json,finished_at) values(?,?,?,?,?,datetime('now'))").run("fetch_json","cbs.units",JSON.stringify({query:{},body:{ilKodu:26},context:{ilKodu:26}}),"completed",JSON.stringify([{birimId:"OBSERVED-UNIT",birimAdi:"Eskişehir Cumhuriyet Başsavcılığı"}]));
db.prepare("insert into cases(id,external_id,court,court_file_no,case_type,status,client_name) values(?,?,?,?,?,?,?)").run(901,"fixture:cbs:901","Eskişehir Cumhuriyet Başsavcılığı","2026/51832","Soruşturma","open","Fixture Müvekkil");
const backup={schema:1,verified:true,queueIdDigest:policy.digest([])};
policy.migrate(db,{expectedQueued:0,backupManifest:backup,migrationId:"fixture-zero"});
const service=policy.install(db,uyap);
const support=service.status(901);
must(support.supported===true&&support.adapter==="cbs_unit_status_exact_v1","CBS exact-list support missing: "+JSON.stringify(support));
must(support.documentBindingAllowed===false,"CBS support must not imply document ownership");
const key=crypto.randomUUID();
const started=service.begin(901,{requestKey:key,refresh:true});
must(started.state==="queued"&&started.adapter==="cbs_unit_status_exact_v1","CBS user query not queued");
const first=uyap.claimNext("avukat.uyap.gov.tr","query");
must(first&&Number(first.id)===Number(started.commandId)&&first.endpointKey==="cbs.search","first CBS page not claimed");
must(first.payload.context.explicitCbsCaseLookup===true&&first.payload.body.pageNumber===1,"CBS query scope wrong");
must(!("dosyaNo" in first.payload.body)&&first.payload.body.birimTuru2==="OBSERVED-UNIT","unobserved direct-number field leaked");
const rows=Array.from({length:500},(_,i)=>({birimId:"OBSERVED-UNIT",dosyaNo:"2025/"+(i+1),dosyaId:"fixture-page1-"+i,dosyaDurumKod:0}));
let result=uyap.reportResult(first.id,{ok:true,status:200,contentType:"application/json",data:[rows,501]});
must(result.ok===true,"first CBS page rejected");
const second=uyap.claimNext("avukat.uyap.gov.tr","query");
must(second&&second.endpointKey==="cbs.search"&&second.payload.body.pageNumber===2,"second scoped CBS page not queued");
const target={birimId:"OBSERVED-UNIT",dosyaNo:"2026/51832",dosyaId:"fixture-opaque-901",dosyaDurumKod:0};
result=uyap.reportResult(second.id,{ok:true,status:200,contentType:"application/json",data:[[target],501]});
must(result.ok===true,"second CBS page rejected");
const c=db.prepare("select * from cases where id=901").get();
must(c.uyap_dosya_id==="fixture-opaque-901"&&String(c.uyap_birim_id)==="OBSERVED-UNIT","exact CBS identity not bound");
const binding=db.prepare("select * from uyap_case_query_bindings where case_id=901").get();
must(binding?.adapter==="cbs_unit_status_exact_v1","CBS binding evidence missing");
const hist=service.history(901);
must(hist[0]?.operation==="cbs.search"&&hist[0]?.state==="completed","CBS history did not complete: "+JSON.stringify(hist));
must(service.downloadOptions(901).length===0,"CBS identity query exposed documents without ownership proof");
const q=uyap.queue(100);
must(!q.some(x=>x.endpoint_key==="document.list"||x.command_type==="download_document"),"CBS identity lookup triggered document/download work");
must(uyap.sessionState().manualDownloadPaused===true,"CBS query changed manual download pause");
const cached=service.begin(901,{requestKey:crypto.randomUUID(),refresh:false});
must(cached.state==="cache_hit","CBS cache-first behavior missing");
const unrelated=db.prepare("select count(*) n from cases where id<>901").get().n;
must(unrelated===0,"CBS query bulk-upserted unrelated files");
console.log(JSON.stringify({ok:true,pages:2,exactLocalMatch:true,history:true,cacheFirst:true,noBulkUpsert:true,noDocumentImport:true,manualPausePreserved:true}));
try{db.close()}catch{}
fs.rmSync(root,{recursive:true,force:true});
