'use strict';
const fs=require('fs'),os=require('os'),path=require('path'),assert=require('assert/strict'),net=require('net'),crypto=require('crypto'),{spawn,spawnSync}=require('child_process');
const {operate,inspect}=require('./package_operations'),{transition}=require('./query_transition');
(async()=>{const bundle=path.resolve(process.argv[2]),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'bono-query-package-')),root=path.join(tmp,'app'),source=path.join(root,'data','source.db'),back=path.join(tmp,'backup');fs.mkdirSync(path.dirname(source),{recursive:true});
for(const dir of ['bridge','web','extension'])fs.cpSync(path.join(__dirname,'..',dir),path.join(root,dir),{recursive:true});
const m=JSON.parse(fs.readFileSync(path.join(bundle,'version-manifest.json')));for(const f of m.files){const dest=path.join(root,f.path);if(f.beforeSha256){fs.mkdirSync(path.dirname(dest),{recursive:true});fs.copyFileSync(path.join(bundle,'rollback',f.path),dest);}else if(fs.existsSync(dest))fs.unlinkSync(dest);}
process.env.BONO_DB_PATH=source;process.env.USERPROFILE=tmp;const db=require('../bridge/db');db.prepare("INSERT OR REPLACE INTO app_settings(key,value) VALUES('uyap_manual_download_pause','1')").run();db.prepare("INSERT INTO uyap_endpoints(endpoint_key,method,host,path) VALUES('case.search','POST','avukat.uyap.gov.tr','/avukat_mahkemeleri_sorgula.ajx')").run();for(let i=0;i<270;i++)db.prepare("INSERT INTO uyap_command_queue(command_type,endpoint_key,payload_json) VALUES('fetch_json','case.search','{}')").run();db.close();
const port=await new Promise(r=>{const s=net.createServer();s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>r(p));});});
assert.equal(inspect(bundle,root).state,'original');
assert.equal((await transition(root,source,back,'BackupOnly',port)).queueCommandIds.length,270);
const occupied=net.createServer();await new Promise(r=>occupied.listen(port,'127.0.0.1',r));await assert.rejects(()=>operate(bundle,root,'Apply',port));await new Promise(r=>occupied.close(r));
await assert.rejects(()=>operate(bundle,root,'Apply',port,{afterFile:n=>{if(n===2)throw Error('synthetic_interruption');}}));assert.equal(inspect(bundle,root).state,'partial');
const quote=s=>"'"+s.replaceAll("'","''")+"'";
const cmd="function Get-CimInstance { @() }; & "+quote(path.join(bundle,'observation_package.ps1'))+' -TargetRoot '+quote(root)+' -Mode Apply -CorePort '+port+' -NodeExe '+quote(process.execPath)+'; exit $LASTEXITCODE';
const ps=spawnSync('powershell',['-NoProfile','-Command',cmd],{encoding:'utf8'});assert.equal(ps.status,0,ps.stdout+ps.stderr);
await operate(bundle,root,'Apply',port);assert.equal(inspect(bundle,root).state,'installed');
const migrationCmd="function Get-CimInstance { @() }; & "+quote(path.join(bundle,'query_transition.ps1'))+' -TargetRoot '+quote(root)+' -SourceDB '+quote(source)+' -BackupDir '+quote(back)+' -Mode BackupMigrate -CorePort '+port+' -NodeExe '+quote(process.execPath)+'; exit $LASTEXITCODE';
const migrationPS=spawnSync('powershell',['-NoProfile','-Command',migrationCmd],{encoding:'utf8'});assert.equal(migrationPS.status,0,migrationPS.stdout+migrationPS.stderr);assert(JSON.parse(migrationPS.stdout).retired===270);assert((await transition(root,source,back,'BackupMigrate',port)).alreadyApplied);
const {DatabaseSync}=require('node:sqlite'),policy=require('../bridge/uyap_user_queries'),seed=new DatabaseSync(source);seed.exec("INSERT OR REPLACE INTO app_settings(key,value) VALUES('uyap_integration_mode','browser_readonly'),('uyap_session_state','ready');INSERT INTO cases(id,court,court_file_no,uyap_birim_id,uyap_dosya_id) VALUES(1,'Fixture Hukuk Mahkemesi','2020/1','unit','fixture-file');INSERT INTO uyap_endpoints(endpoint_key,method,host,path,enabled) VALUES('document.list','POST','avukat.uyap.gov.tr','/list_dosya_evraklar.ajx',1)");policy.certifyBinding(seed,{kind:'verified_portal_binding',caseId:1,unitId:'unit',caseNo:'2020/1',dosyaId:'fixture-file',adapter:'court_documents_v1',evidenceRef:'observation:'+crypto.randomUUID()});seed.close();
// Real generated live overlay, remapping only its fixed loopback port for the fixture.
const sp=path.join(root,'bridge/server.js'),installed=fs.readFileSync(sp,'utf8');fs.writeFileSync(sp,installed.replace('const PORT=47831;','const PORT='+port+';'));
let child;async function boot(){child=spawn(process.execPath,[sp],{cwd:root,env:{...process.env,BONO_DB_PATH:source,USERPROFILE:tmp,BONO_DISABLE_WORKER:'0',BONO_UYAP_EXECUTION_HOLD:'0'},stdio:'ignore',windowsHide:true});for(let i=0;i<100;i++){try{const h=await(await fetch('http://127.0.0.1:'+port+'/health')).json();assert.equal(h.userQueryPolicy,'user_controlled');return;}catch{}await new Promise(r=>setTimeout(r,30));}throw Error('overlay_boot_failed');}
async function stop(){await new Promise(r=>{child.once('exit',r);child.kill();});}
try{for(let i=0;i<2;i++){await boot();for(const lane of ['query','download','any']){const r=await fetch('http://127.0.0.1:'+port+'/api/uyap/commands/next?lane='+lane);assert.equal(r.status,204);}const history=await(await fetch('http://127.0.0.1:'+port+'/api/uyap/query-history?limit=200')).json();assert.equal(history.length,200);assert(history.every(h=>h.state==='archived_never_executed'));await new Promise(r=>setTimeout(r,1000));await stop();}
await boot();const base='http://127.0.0.1:'+port,headers={'Content-Type':'application/json','X-Bono-User-Action':'1'};
const q=await(await fetch(base+'/api/uyap/cases/1/query',{method:'POST',headers,body:JSON.stringify({requestKey:crypto.randomUUID()})})).json();assert(q.commandId>270,JSON.stringify(q));
const claim=await(await fetch(base+'/api/uyap/commands/next?host=avukat.uyap.gov.tr&lane=query')).json();assert.equal(claim.id,q.commandId);
const result=await(await fetch(base+'/api/uyap/commands/'+claim.id+'/result',{method:'POST',headers,body:JSON.stringify({ok:true,status:200,data:{tumEvraklar:[]}})})).json();assert.equal(result.ok,true);
const cached=await(await fetch(base+'/api/uyap/cases/1/query',{method:'POST',headers,body:JSON.stringify({requestKey:crypto.randomUUID()})})).json();assert.equal(cached.state,'cache_hit');await stop();
await transition(root,source,back,'RollbackHold',port);const read=new DatabaseSync(source,{readOnly:true});assert.equal(read.prepare("SELECT count(*) n FROM uyap_command_queue WHERE status='archived'").get().n,270);assert.equal(read.prepare("SELECT value FROM app_settings WHERE key='uyap_manual_download_pause'").get().value,'1');assert.equal(read.prepare('SELECT state FROM uyap_query_policy').get().state,'rollback_hold');read.close();
fs.writeFileSync(sp,installed);await operate(bundle,root,'Rollback',port);assert.equal(inspect(bundle,root).state,'original');
console.log(JSON.stringify({ok:true,actualLiveOverlay:true,explicitQueryAndCacheOnActualOverlay:true,syntheticDB:true,backupVerified:true,powerShellWrappersExercisedWithSyntheticInventory:true,occupiedPortBlocked:true,partialInstallResumed:true,idempotent:true,restartDoesNotRevive270:true,holdRollbackRetainsHistory:true,sourceRollbackExact:true,portalRequests:0}));
}finally{if(child&&child.exitCode===null)await stop();}})().catch(e=>{console.error(e);process.exitCode=1;});
